@server=http://localhost:4004
@username=davi
@password=123456


### Backups
# @name Backups_GET
GET {{server}}/apps/dflc/cap/GestorDeGastos/Backup/Backups
Authorization: Basic {{username}}:{{password}}


### Backups Drafts GET
# @name Backups_Drafts_GET
GET {{server}}/apps/dflc/cap/GestorDeGastos/Backup/Backups?$filter=(IsActiveEntity eq false)
Authorization: Basic {{username}}:{{password}}


### Backups Drafts GET
# @name Backups_Drafts_and_Actives_merge
GET {{server}}/apps/dflc/cap/GestorDeGastos/Backup/Backups?$count=true&$expand=DraftAdministrativeData($select=DraftUUID,InProcessByUser)&$filter=(IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null)&$skip=0&$top=30 
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:pt-BR
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true
Authorization: Basic {{username}}:{{password}}


### Backups Draft POST
# @name Backups_Draft_POST
POST {{server}}/apps/dflc/cap/GestorDeGastos/Backup/Backups
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "BackupType": "BackupType-13126129"
}


### Result from POST request above
@draftID={{Backups_Draft_POST.response.body.$.ID}}


### Backups Draft PATCH
# @name Backups_Draft_Patch
PATCH {{server}}/apps/dflc/cap/GestorDeGastos/Backup/Backups(ID={{draftID}},IsActiveEntity=false)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "BackupType": "BackupType-13126129"
}


### Backups Draft Prepare
# @name Backups_Draft_Prepare
POST {{server}}/apps/dflc/cap/GestorDeGastos/Backup/Backups(ID={{draftID}},IsActiveEntity=false)/BackupService.draftPrepare
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### Backups Draft Activate
# @name Backups_Draft_Activate
POST {{server}}/apps/dflc/cap/GestorDeGastos/Backup/Backups(ID={{draftID}},IsActiveEntity=false)/BackupService.draftActivate
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### Backups Draft Activate
# @name Backups_Draft_Inactivate
POST {{server}}/apps/dflc/cap/GestorDeGastos/Backup/Backups(ID={{draftID}},IsActiveEntity=true)/draftEdit
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}