@server=http://localhost:4004
@username=beatriz
@password=123456


### Shares
# @name Shares_GET
GET {{server}}/apps/dflc/cap/ExpenseManager/Share/Shares?$expand=Entities
Authorization: Basic {{username}}:{{password}}


### Shares Drafts GET
# @name Shares_Drafts_GET
GET {{server}}/apps/dflc/cap/ExpenseManager/Share/Shares?$filter=(IsActiveEntity eq false)&$expand=DraftAdministrativeData($select=InProcessByUser,LastChangedByUser)&$orderby=modifiedAt desc
Authorization: Basic {{username}}:{{password}}


### Shares Drafts GET
# @name Shares_Drafts_and_Actives_merge
GET {{server}}/apps/dflc/cap/ExpenseManager/Share/Shares?$count=true&$expand=DraftAdministrativeData($select=DraftUUID,InProcessByUser)&$filter=(IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null)&$skip=0&$top=30 
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:pt-BR
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true
Authorization: Basic {{username}}:{{password}}


### Shares Draft POST
# @name Shares_Draft_POST
POST {{server}}/apps/dflc/cap/ExpenseManager/Share/Shares
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Person": {
    "ID": "11111111-1111-1111-1111-111111111111"
  },
  "User": "User-18986079",
  "Entities": [
    {
      "Entity": 6,
      "Permission": 3,
      "createdAt": "2000-10-01T00:00:00.000Z",
      "createdBy": "createdBy.fb4dt@example.com",
      "modifiedAt": "2002-09-11T00:00:00.000Z",
      "modifiedBy": "modifiedBy.fb4dt@example.com"
    },
    {
      "Entity": 6,
      "Permission": 3,
      "createdAt": "2006-07-18T00:00:00.000Z",
      "createdBy": "createdBy.fb4du@example.org",
      "modifiedAt": "2010-12-24T00:00:00.000Z",
      "modifiedBy": "modifiedBy.fb4du@example.com"
    }
  ]
}


### Result from POST request above
@draftID={{Shares_Draft_POST.response.body.$.ID}}


### Shares Draft PATCH
# @name Shares_Draft_Patch
PATCH {{server}}/apps/dflc/cap/ExpenseManager/Share/Shares(ID={{draftID}},IsActiveEntity=false)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Person": {
    "ID": "11111111-1111-1111-1111-111111111111"
  },
  "User": "teste"
}


### Shares Draft Prepare
# @name Shares_Draft_Prepare
POST {{server}}/apps/dflc/cap/ExpenseManager/Share/Shares(ID={{draftID}},IsActiveEntity=false)/ShareService.draftPrepare
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### Shares Draft Activate
# @name Shares_Draft_Activate
POST {{server}}/apps/dflc/cap/ExpenseManager/Share/Shares(ID={{draftID}},IsActiveEntity=false)/draftActivate
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### Shares Draft Inactivate
# @name Shares_Draft_Inactivate
POST {{server}}/apps/dflc/cap/ExpenseManager/Share/Shares(ID={{draftID}},IsActiveEntity=true)/draftEdit
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### Shares Delete
# @name Shares_DELETE_Active
DELETE {{server}}/apps/dflc/cap/ExpenseManager/Share/Shares(ID={{draftID}},IsActiveEntity=true)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### Shares Delete Draft
# @name Shares_DELETE_draft
DELETE {{server}}/apps/dflc/cap/ExpenseManager/Share/Shares(ID={{draftID}},IsActiveEntity=false)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}