{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Currencies_texts",
        "Service": "/ExpenseManager/Services/ExpenseManager.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "locale": "#Page:Currencies_texts_Edit/#Control:locale/#Value",
        "name": "#Page:Currencies_texts_Edit/#Control:name/#Value",
        "descr": "#Page:Currencies_texts_Edit/#Control:descr/#Value",
        "code": "#Page:Currencies_texts_Edit/#Control:code/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/ExpenseManager/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/ExpenseManager/Actions/UpdateEntityFailureMessage.action"
}