{
    "CreateLinks": [],
    "OnFailure": "/ExpenseManager/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/ExpenseManager/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "locale": "#Page:Currencies_texts_Create/#Control:locale/#Value",
        "name": "#Page:Currencies_texts_Create/#Control:name/#Value",
        "descr": "#Page:Currencies_texts_Create/#Control:descr/#Value",
        "code": "#Page:Currencies_texts_Create/#Control:code/#Value"
    },
    "Target": {
        "EntitySet": "Currencies_texts",
        "Service": "/ExpenseManager/Services/ExpenseManager.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}