{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Categories",
        "Service": "/ExpenseManager/Services/ExpenseManager.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Name": "#Page:Categories_Edit/#Control:Name/#Value",
        "ImageType": "#Page:Categories_Edit/#Control:ImageType/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/ExpenseManager/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/ExpenseManager/Actions/UpdateEntityFailureMessage.action"
}