{
    "CreateLinks": [],
    "OnFailure": "/ExpenseManager/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/ExpenseManager/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Year": "#Page:Invoices_Create/#Control:Year/#Value",
        "Month": "#Page:Invoices_Create/#Control:Month/#Value",
        "Description": "#Page:Invoices_Create/#Control:Description/#Value",
        "TotalAmount": "#Page:Invoices_Create/#Control:TotalAmount/#Value",
        "Currency_code": "#Page:Invoices_Create/#Control:Currency_code/#SelectedValue",
        "InvoiceSent": "#Page:Invoices_Create/#Control:InvoiceSent/#Value"
    },
    "Target": {
        "EntitySet": "Invoices",
        "Service": "/ExpenseManager/Services/ExpenseManager.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}