{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Invoices",
        "Service": "/ExpenseManager/Services/ExpenseManager.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Year": "#Page:Invoices_Edit/#Control:Year/#Value",
        "Month": "#Page:Invoices_Edit/#Control:Month/#Value",
        "Description": "#Page:Invoices_Edit/#Control:Description/#Value",
        "TotalAmount": "#Page:Invoices_Edit/#Control:TotalAmount/#Value",
        "Currency_code": "#Page:Invoices_Edit/#Control:Currency_code/#SelectedValue",
        "InvoiceSent": "#Page:Invoices_Edit/#Control:InvoiceSent/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/ExpenseManager/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/ExpenseManager/Actions/UpdateEntityFailureMessage.action"
}