{
    "CreateLinks": [],
    "OnFailure": "/ExpenseManager/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/ExpenseManager/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Name": "#Page:Categories_Create/#Control:Name/#Value",
        "ImageType": "#Page:Categories_Create/#Control:ImageType/#Value"
    },
    "Target": {
        "EntitySet": "Categories",
        "Service": "/ExpenseManager/Services/ExpenseManager.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}