{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/ExpenseManager/Pages/ExpenseManager_Liabilities/Liabilities_CreateLiabilityTransactions.page",
    "_Type": "Action.Type.Navigation"
}