{
    "PopoverItems": [{
            "Title": "Open Document",
            "OnPress": "/ExpenseManager/Actions/ExpenseManager/Backups/Backups_OpenDocument.action"
        },
        {
            "Title": "Delete",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Backups/Backups_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}