{
    "PopoverItems": [{
            "Title": "Add Entities",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Shares/NavToShares_CreateEntities.js"
        },
        {
            "Title": "Delete",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Shares/Shares_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}