{
    "PopoverItems": [{
            "Title": "Open Document",
            "OnPress": "/ExpenseManager/Actions/ExpenseManager/Cards/Cards_OpenDocument.action"
        },
        {
            "Title": "Add Invoices",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Cards/NavToCards_CreateInvoices.js"
        },
        {
            "Title": "Delete",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Cards/Cards_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}