{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Cards",
        "Service": "/ExpenseManager/Services/ExpenseManager.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Name": "#Page:Cards_Edit/#Control:Name/#Value",
        "ImageType": "#Page:Cards_Edit/#Control:ImageType/#Value",
        "Limit": "#Page:Cards_Edit/#Control:Limit/#Value",
        "Currency_code": "#Page:Cards_Edit/#Control:Currency_code/#SelectedValue",
        "DueDay": "#Page:Cards_Edit/#Control:DueDay/#Value",
        "ClosingDay": "#Page:Cards_Edit/#Control:ClosingDay/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/ExpenseManager/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/ExpenseManager/Actions/UpdateEntityFailureMessage.action"
}