{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Transactions",
        "Service": "/ExpenseManager/Services/ExpenseManager.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Date": "#Page:Transactions_Edit/#Control:Date/#Value",
        "TotalAmount": "#Page:Transactions_Edit/#Control:TotalAmount/#Value",
        "Amount": "#Page:Transactions_Edit/#Control:Amount/#Value",
        "Currency_code": "#Page:Transactions_Edit/#Control:Currency_code/#SelectedValue",
        "TotalInstallments": "#Page:Transactions_Edit/#Control:TotalInstallments/#Value",
        "Installment": "#Page:Transactions_Edit/#Control:Installment/#Value",
        "Description": "#Page:Transactions_Edit/#Control:Description/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/ExpenseManager/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/ExpenseManager/Actions/UpdateEntityFailureMessage.action"
}