{
    "CreateLinks": [],
    "OnFailure": "/ExpenseManager/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/ExpenseManager/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "name": "#Page:Currencies_Create/#Control:name/#Value",
        "descr": "#Page:Currencies_Create/#Control:descr/#Value",
        "code": "#Page:Currencies_Create/#Control:code/#Value",
        "symbol": "#Page:Currencies_Create/#Control:symbol/#Value",
        "minorUnit": "#Page:Currencies_Create/#Control:minorUnit/#Value"
    },
    "Target": {
        "EntitySet": "Currencies",
        "Service": "/ExpenseManager/Services/ExpenseManager.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}