{
    "CreateLinks": [],
    "OnFailure": "/ExpenseManager/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/ExpenseManager/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Type": "#Page:LiabilityTransactions_Create/#Control:Type/#Value",
        "Description": "#Page:LiabilityTransactions_Create/#Control:Description/#Value",
        "MovementDate": "#Page:LiabilityTransactions_Create/#Control:MovementDate/#Value",
        "Installment": "#Page:LiabilityTransactions_Create/#Control:Installment/#Value",
        "TotalInstallments": "#Page:LiabilityTransactions_Create/#Control:TotalInstallments/#Value",
        "Amount": "#Page:LiabilityTransactions_Create/#Control:Amount/#Value",
        "Currency_code": "#Page:LiabilityTransactions_Create/#Control:Currency_code/#SelectedValue",
        "BalanceAfter": "#Page:LiabilityTransactions_Create/#Control:BalanceAfter/#Value",
        "IsAutomatic": "#Page:LiabilityTransactions_Create/#Control:IsAutomatic/#Value",
        "ExternalReference": "#Page:LiabilityTransactions_Create/#Control:ExternalReference/#Value"
    },
    "Target": {
        "EntitySet": "LiabilityTransactions",
        "Service": "/ExpenseManager/Services/ExpenseManager.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}