{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/ExpenseManager/Pages/ExpenseManager_LiabilityTransactions/LiabilityTransactions_Create.page",
    "_Type": "Action.Type.Navigation"
}