{
    "PopoverItems": [{
            "Title": "Add LiabilityTransactions",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Liabilities/NavToLiabilities_CreateLiabilityTransactions.js"
        },
        {
            "Title": "Delete",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Liabilities/Liabilities_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}