{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Liabilities",
        "Service": "/ExpenseManager/Services/ExpenseManager.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Name": "#Page:Liabilities_Edit/#Control:Name/#Value",
        "Creditor": "#Page:Liabilities_Edit/#Control:Creditor/#Value",
        "Description": "#Page:Liabilities_Edit/#Control:Description/#Value",
        "Type": "#Page:Liabilities_Edit/#Control:Type/#Value",
        "Status": "#Page:Liabilities_Edit/#Control:Status/#Value",
        "OriginalAmount": "#Page:Liabilities_Edit/#Control:OriginalAmount/#Value",
        "CurrentBalance": "#Page:Liabilities_Edit/#Control:CurrentBalance/#Value",
        "PaidAmount": "#Page:Liabilities_Edit/#Control:PaidAmount/#Value",
        "Currency_code": "#Page:Liabilities_Edit/#Control:Currency_code/#SelectedValue",
        "InterestMode": "#Page:Liabilities_Edit/#Control:InterestMode/#Value",
        "InterestRate": "#Page:Liabilities_Edit/#Control:InterestRate/#Value",
        "Installments": "#Page:Liabilities_Edit/#Control:Installments/#Value",
        "InstallmentAmount": "#Page:Liabilities_Edit/#Control:InstallmentAmount/#Value",
        "StartDate": "#Page:Liabilities_Edit/#Control:StartDate/#Value",
        "FirstDueDate": "#Page:Liabilities_Edit/#Control:FirstDueDate/#Value",
        "EndDate": "#Page:Liabilities_Edit/#Control:EndDate/#Value",
        "LastPaymentDate": "#Page:Liabilities_Edit/#Control:LastPaymentDate/#Value",
        "ExternalReference": "#Page:Liabilities_Edit/#Control:ExternalReference/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/ExpenseManager/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/ExpenseManager/Actions/UpdateEntityFailureMessage.action"
}