{
    "PopoverItems": [{
            "Title": "Open Document",
            "OnPress": "/ExpenseManager/Actions/ExpenseManager/Persons/Persons_OpenDocument.action"
        },
        {
            "Title": "Add Shares",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Persons/NavToPersons_CreateShares.js"
        },
        {
            "Title": "Add Categories",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Persons/NavToPersons_CreateCategories.js"
        },
        {
            "Title": "Add Cards",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Persons/NavToPersons_CreateCards.js"
        },
        {
            "Title": "Delete",
            "OnPress": "/ExpenseManager/Rules/ExpenseManager/Persons/Persons_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}