{
    "ParentLink": {
        "Property": "Cards",
        "Target": {
            "EntitySet": "Persons",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/ExpenseManager/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/ExpenseManager/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "Name": "#Page:Persons_CreateCards/#Control:Name/#Value",
        "ImageType": "#Page:Persons_CreateCards/#Control:ImageType/#Value",
        "Limit": "#Page:Persons_CreateCards/#Control:Limit/#Value",
        "Currency_code": "#Page:Persons_CreateCards/#Control:Currency_code/#SelectedValue",
        "DueDay": "#Page:Persons_CreateCards/#Control:DueDay/#Value",
        "ClosingDay": "#Page:Persons_CreateCards/#Control:ClosingDay/#Value"
    },
    "Target": {
        "EntitySet": "Cards",
        "Service": "/ExpenseManager/Services/ExpenseManager.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}